# SITE CONFIGURATION
baseurl: ""
url: "https://alfonsomozkoh.github.io"
title: Alfonso Mozko H. # site's title
description: "Un estudiante de informática" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Alfonso Mozko H. # blog's title
  avatar: assets/img/alfonsomozkohme.png
  favicon: assets/alfonsomozkoico.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Un Estudiante <br> de Informática</p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
   Creado con <a href="https://jekyllrb.com/">Jekyll</a> editado por <a href="https://www.facebook.com/UnEstudianteDeInformatica/">Alfonso Mozko H.</a>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: "alfonsomozkoh@vivaldi.net" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "UnEstudianteDeInformatica"
  flickr:
  gitlab:
  github: "alfonsomozkoh"
  google_plus:
  instagram: "alfonsomozkoh"
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: "UA-116376962-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: alfonsomozkoh
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Sígueme"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Siguiente post"
  str_previous_post: "Post previo"
  str_next_page: "Siguiente"
  str_previous_page: "Previo"
  str_continue_reading: "Seguir leyendo"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: false
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
