---
title: Alfonso Mozko H.
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
url: https://alfonsomozkoh.github.io
description: Un estudiante de informática
theme_settings:
  title: Alfonso Mozko H. | Un estudiante de informática
  avatar: assets/img/alfonsomozkohme.png
  favicon: assets/alfonsomozkoico.ico
  gravatar: 
  header_text: "<p> alfonsomozkoh@UnEstudianteDeInformática:~$ <br> Conocimiento compartido
    </p>\n"
  header_text_feature_image: assets/img/pexels/anon.png
  footer_text: 'Creado con <a href="https://jekyllrb.com/">Jekyll</a> editado por
    <a href="https://www.facebook.com/UnEstudianteDeInformatica/">Alfonso Mozko H.</a>

'
  rss: true
  email_address: alfonsomozkoh@vivaldi.net
  behance: 
  bitbucket: 
  dribbble: 
  facebook: UnEstudianteDeInformatica
  flickr: 
  gitlab: 
  github: AlfonsoJazz
  google_plus: 
  instagram: alfonsomozkoh
  keybase: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: 
  steam: 76561198248270050
  tumblr: 
  twitter: AlfonsoMozkoH
  vimeo: 
  wordpress: 
  youtube: 
  google_analytics: UA-116376962-1
  disqus_shortname: alfonsomozkoh
  katex: true
  special_page:
    search:
      icon: search
      enabled: true
    tags:
      icon: tags
      enabled: true
  str_follow_on: Sígueme
  str_rss_follow: Follow RSS feed
  str_email: Email
  str_next_post: Siguiente post
  str_previous_post: Post previo
  str_next_page: Siguiente
  str_previous_page: Previo
  str_continue_reading: Seguir leyendo
  str_javascript_required_disqus: Please enable JavaScript to view comments.
  google_fonts: Source+Sans+Pro:400,700,700italic,400italic
  post_navigation: true
paginate: 10
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- type-on-strap.gemspec
- "*.gem"
- LICENSE
- README.md
- screenshot.png
